# -*- coding: utf-8 -*-
"""NIH_visual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUFu3_W66-luF6Rni7nyr4J70vz5DR9S
"""

# 1. Mount Google Drive to access your saved CSV
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import urllib.request
import zipfile

# 1. Load the required image names from the CSV
csv_path = '/content/drive/MyDrive/msc_medical_vlm_weights_final/nih_chestxray/BBox_List_2017.csv'
df = pd.read_csv(csv_path)
csv_dir = os.path.dirname(csv_path)

required_images = set(df['Image Index'].unique())
print(f"Found {len(required_images)} unique images to extract.")

# 2. Set the output directory to be 'images' inside the CSV directory
output_dir = os.path.join(csv_dir, 'images')
os.makedirs(output_dir, exist_ok=True)
print(f"Images will be saved to: {output_dir}")

# 3. Permanent Hugging Face Mirrors for the 12 ZIP files
hf_base = "https://huggingface.co/datasets/alkzar90/NIH-Chest-X-ray-dataset/resolve/main/data/images/"
zip_files = [f"images_{str(i).zfill(3)}.zip" for i in range(1, 13)]

# Local temporary path in Colab (does NOT use your Google Drive quota)
temp_zip_path = '/content/temp_images.zip'

for idx, zip_name in enumerate(zip_files):
    # Stop early if we've already found all 880 images!
    if not required_images:
        print("\nAll required images successfully downloaded!")
        break

    download_url = hf_base + zip_name
    print(f"\n[{idx + 1}/12] Downloading {zip_name} from Hugging Face...")

    try:
        # Download the zip file to local Colab storage
        urllib.request.urlretrieve(download_url, temp_zip_path)

        # Open the zip and scan for matching bounding-box images
        print(f"Scanning inside {zip_name}...")
        with zipfile.ZipFile(temp_zip_path, 'r') as z:
            for file_info in z.infolist():
                # Get the filename (ignoring any internal folders inside the zip)
                filename = os.path.basename(file_info.filename)

                # If the file matches one we need, extract it!
                if filename in required_images:
                    print(f" -> Found and extracting: {filename}")

                    # Write the file directly to your Google Drive folder
                    with z.open(file_info.filename) as source, \
                         open(os.path.join(output_dir, filename), 'wb') as target:
                        target.write(source.read())

                    # Remove it from our checklist
                    required_images.remove(filename)

                # If we finish finding all images mid-archive, stop scanning
                if not required_images:
                    break

    except Exception as e:
        print(f"Error processing {zip_name}: {e}")

    finally:
        # CLEANUP: Delete the 2GB temp file so Colab doesn't crash from full storage
        if os.path.exists(temp_zip_path):
            os.remove(temp_zip_path)

print(f"\nFinished. Missed {len(required_images)} images.")

!pip install -U bitsandbytes>=0.46.1

import os
import re
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random
import matplotlib.pyplot as plt
from transformers import AutoImageProcessor, AutoModel, AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel

# ==============================================================================
# PART 1: ARCHITECTURE & WEIGHT LOADING
# ==============================================================================
device = "cuda" if torch.cuda.is_available() else "cpu"
print("1. Initializing Architecture...")

vision_processor = AutoImageProcessor.from_pretrained("microsoft/rad-dino")
vision_encoder = AutoModel.from_pretrained("microsoft/rad-dino").to(device)
vision_encoder.eval()

llm_id = "Qwen/Qwen2.5-3B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(llm_id)
tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)
base_llm = AutoModelForCausalLM.from_pretrained(llm_id, quantization_config=bnb_config, device_map={"": 0})

class QFormerProjector(nn.Module):
    def __init__(self, num_queries=64, vision_dim=768, llm_dim=3584):
        super().__init__()
        self.query_tokens = nn.Parameter(torch.randn(1, num_queries, vision_dim))
        self.cross_attn = nn.MultiheadAttention(embed_dim=vision_dim, num_heads=8, batch_first=True)
        self.norm1 = nn.LayerNorm(vision_dim)
        self.ffn = nn.Sequential(nn.Linear(vision_dim, vision_dim * 4), nn.GELU(), nn.Linear(vision_dim * 4, vision_dim))
        self.norm2 = nn.LayerNorm(vision_dim)
        self.proj = nn.Linear(vision_dim, llm_dim)
        self.llm_norm = nn.LayerNorm(llm_dim)

    def forward(self, patch_embeddings, return_attention=False):
        spatial_patches = patch_embeddings[:, 1:, :]
        batch_size = spatial_patches.shape[0]
        queries = self.query_tokens.expand(batch_size, -1, -1)
        attn_output, attn_weights = self.cross_attn(
            query=queries, key=spatial_patches, value=spatial_patches,
            need_weights=True, average_attn_weights=True
        )
        x = self.norm1(queries + attn_output)
        x = self.norm2(x + self.ffn(x))
        out = self.llm_norm(self.proj(x))
        if return_attention: return out, attn_weights
        return out

projector = QFormerProjector(num_queries=64, vision_dim=768, llm_dim=base_llm.config.hidden_size).to(device)

LOAD_DIR = "/content/drive/MyDrive/msc_medical_vlm_weights_final/checkpoint-epoch-6"
print(f"Loading weights from {LOAD_DIR}...")
projector.load_state_dict(torch.load(os.path.join(LOAD_DIR, "vision_projector.pth"), map_location=device))
efficient_llm = PeftModel.from_pretrained(base_llm, os.path.join(LOAD_DIR, "qwen_lora_adapters"))

projector.eval()
efficient_llm.eval()

# ==============================================================================
# PART 2: TARGET-FREE XAI ENGINE (WITH RANDOM TRAINING PROMPTS)
# ==============================================================================
print("2. Booting Target-Free XAI Engine...")

def get_random_clinical_prompt():
    """Matches your exact training distribution."""
    instructions = [
        "Analyze this chest radiograph and generate a concise clinical report.",
        "Review this CXR and detail findings for the lungs, heart, and pleura.",
        "Provide a structured diagnostic report for this chest X-ray using standard radiology terminology."
    ]
    return (
        "<|im_start|>system\n"
        "You are an expert radiologist. Write ONLY the diagnostic narrative.<|im_end|>\n"
        f"<|im_start|>user\n{random.choice(instructions)}<|im_end|>\n"
        "<|im_start|>assistant\n"
    )

def generate_report(image, prompt_text):
    pv = vision_processor(images=image, return_tensors='pt').pixel_values.to(device)
    with torch.no_grad():
        with torch.amp.autocast(device_type="cuda", dtype=torch.float16):
            patch_emb = vision_encoder(pv).last_hidden_state.to(torch.float16)
            visual_prompts = projector(patch_emb)
            prompt_ids = tokenizer(prompt_text, return_tensors="pt").input_ids.to(device)
            prompt_embeds = efficient_llm.get_input_embeddings()(prompt_ids)
            inputs_embeds = torch.cat([visual_prompts, prompt_embeds], dim=1)
            outputs = efficient_llm.generate(inputs_embeds=inputs_embeds, max_new_tokens=40, do_sample=False)
    return tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

def get_holistic_gradients_and_activations(image, prompt_text):
    gen_text = generate_report(image, prompt_text)
    print(f"  [Model Generated]: '{gen_text}'")

    pv = vision_processor(images=image, return_tensors='pt').pixel_values.to(device)
    with torch.no_grad():
        dino_out = vision_encoder(pv).last_hidden_state.to(torch.float16)

    spatial_patches = dino_out[:, 1:, :].detach().clone()
    spatial_patches.requires_grad_(True)

    with torch.amp.autocast(device_type="cuda", dtype=torch.float16):
        batch_size = spatial_patches.shape[0]
        queries = projector.query_tokens.expand(batch_size, -1, -1)

        attn_output, attn_weights = projector.cross_attn(
            query=queries, key=spatial_patches, value=spatial_patches, need_weights=True, average_attn_weights=True)

        x = projector.norm1(queries + attn_output)
        x = projector.norm2(x + projector.ffn(x))
        visual_prompts = projector.llm_norm(projector.proj(x))

        full_text = prompt_text + gen_text
        full_ids = tokenizer(full_text, return_tensors="pt").input_ids.to(device)
        gen_ids = tokenizer(gen_text, add_special_tokens=False, return_tensors="pt").input_ids.to(device)[0]

        text_embeds = efficient_llm.get_input_embeddings()(full_ids)
        inputs_embeds = torch.cat([visual_prompts, text_embeds], dim=1)

        projector.zero_grad()
        efficient_llm.zero_grad()

        outputs = efficient_llm(inputs_embeds=inputs_embeds[:, :-1, :])
        logits = outputs.logits[0]

        prompt_length = tokenizer(prompt_text, return_tensors="pt").input_ids.shape[1]
        start_idx = 64 + prompt_length - 1

        holistic_score = 0
        for i, token_id in enumerate(gen_ids):
            if start_idx + i < logits.shape[0]:
                holistic_score += logits[start_idx + i, token_id]

    holistic_score.backward()

    return {
        'patches_act': spatial_patches.detach()[0],
        'patches_grad': spatial_patches.grad[0],
        'cross_attn_act': attn_weights.detach()[0],
        'gen_ids': gen_ids,
        'start_idx': start_idx
    }

def format_heatmap(cam_1d, image_size):
    grid_size = int(math.sqrt(cam_1d.shape[0]))
    cam_grid = cam_1d.view(1, 1, grid_size, grid_size)
    upscaled = F.interpolate(cam_grid, size=image_size, mode='bilinear', align_corners=False)
    heatmap = upscaled.squeeze().cpu().numpy()
    if heatmap.max() > 0:
        heatmap = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min() + 1e-8)
    return heatmap

# ==============================================================================
# PART 3: THE TARGET-FREE XAI METHODS
# ==============================================================================

def vlm_cross_attention(image):
    pv = vision_processor(images=image, return_tensors='pt').pixel_values.to(device)
    with torch.no_grad():
        with torch.amp.autocast(device_type="cuda", dtype=torch.float16):
            patch_emb = vision_encoder(pv).last_hidden_state.to(torch.float16)
            _, attn_weights = projector(patch_emb, return_attention=True)
    cam = attn_weights.squeeze(0).mean(dim=0)
    return format_heatmap(cam, image.size[::-1]) # BUG 2 FIX: transposed size

def vlm_gradcam(image, prompt_text):
    data = get_holistic_gradients_and_activations(image, prompt_text)
    weights = data['patches_grad'].mean(dim=0)
    cam = F.relu((data['patches_act'] * weights).sum(dim=-1))
    return format_heatmap(cam, image.size[::-1]) # BUG 2 FIX: transposed size

def vlm_hirescam(image, prompt_text):
    data = get_holistic_gradients_and_activations(image, prompt_text)
    cam = F.relu((data['patches_grad'] * data['patches_act']).sum(dim=-1))
    return format_heatmap(cam, image.size[::-1]) # BUG 2 FIX: transposed size

def vlm_scorecam(image, prompt_text, batch_size=8):
    baseline_data = get_holistic_gradients_and_activations(image, prompt_text)
    gen_ids = baseline_data['gen_ids']
    start_idx = baseline_data['start_idx']

    pv = vision_processor(images=image, return_tensors='pt').pixel_values.to(device)
    H, W = pv.shape[2], pv.shape[3]

    with torch.no_grad():
        with torch.amp.autocast(device_type="cuda", dtype=torch.float16):
            patch_emb = vision_encoder(pv).last_hidden_state.to(torch.float16)


    spatial_patches = patch_emb[0, 1:, :] # shape: [196, 768]
    num_channels = spatial_patches.shape[-1] # 768
    grid_size = int(math.sqrt(spatial_patches.shape[0])) # 14

    # Reshape the 768 spatial feature maps to [768, 1, 14, 14] to act as our masks
    masks_grid = spatial_patches.t().view(num_channels, 1, grid_size, grid_size)

    # Upsample masks to input image resolution
    masks_upscaled = F.interpolate(masks_grid, size=(H, W), mode='bilinear', align_corners=False)

    # Normalize each mask to [0, 1] range individually
    masks_min = masks_upscaled.view(num_channels, -1).min(dim=1)[0].view(num_channels, 1, 1, 1)
    masks_max = masks_upscaled.view(num_channels, -1).max(dim=1)[0].view(num_channels, 1, 1, 1)
    masks = (masks_upscaled - masks_min) / (masks_max - masks_min + 1e-8)

    weights = torch.zeros(num_channels, device=device)

    gen_text = tokenizer.decode(gen_ids)
    full_text = prompt_text + gen_text
    full_ids = tokenizer(full_text, return_tensors="pt").input_ids.to(device)
    text_embeds = efficient_llm.get_input_embeddings()(full_ids)


    baseline_pv = torch.zeros_like(pv)
    with torch.no_grad():
        with torch.amp.autocast(device_type="cuda", dtype=torch.float16):
            b_patch_emb = vision_encoder(baseline_pv).last_hidden_state.to(torch.float16)
            b_visual_prompts = projector(b_patch_emb)
            b_inputs = torch.cat([b_visual_prompts, text_embeds], dim=1)
            b_outputs = efficient_llm(inputs_embeds=b_inputs[:, :-1, :])
            b_logits = b_outputs.logits[0]

            baseline_score = 0
            for i, token_id in enumerate(gen_ids):
                if start_idx + i < b_logits.shape[0]:
                    baseline_score += b_logits[start_idx + i, token_id].item()


    with torch.no_grad():
        with torch.amp.autocast(device_type="cuda", dtype=torch.float16):
            for s in range(0, num_channels, batch_size):
                e = min(s + batch_size, num_channels)
                masked_pv = pv * masks[s:e]
                m_patch_emb = vision_encoder(masked_pv).last_hidden_state.to(torch.float16)
                m_visual_prompts = projector(m_patch_emb)

                batch_text_embeds = text_embeds.expand(m_visual_prompts.shape[0], -1, -1)
                m_inputs = torch.cat([m_visual_prompts, batch_text_embeds], dim=1)
                m_outputs = efficient_llm(inputs_embeds=m_inputs[:, :-1, :])
                m_logits = m_outputs.logits

                for b_idx in range(m_logits.shape[0]):
                    m_holistic_score = 0
                    for i, token_id in enumerate(gen_ids):
                        if start_idx + i < m_logits.shape[1]:
                            m_holistic_score += m_logits[b_idx, start_idx + i, token_id].item()


                    weights[s + b_idx] = m_holistic_score - baseline_score


    weights = weights.view(num_channels, 1, 1)


    scorecam = (weights.cpu() * masks_grid.squeeze(1).cpu()).sum(dim=0)
    scorecam = F.relu(scorecam) # Apply ReLU to only keep positive causal contributions


    return format_heatmap(scorecam.flatten(), image.size[::-1])

# =============================================================================
#  NIH ChestX-ray8 TRANSFER LOCALIZATION EVALUATION  (corrected + hardened)
# =============================================================================
#  Add as a NEW CELL after the cell that defines vlm_cross_attention /
#  vlm_gradcam / vlm_hirescam / vlm_scorecam and get_random_clinical_prompt.
#
#  Computes Pointing Game + IoU on NIH ChestX-ray8 boxes (transfer test).
#  Does NOT touch deletion/insertion AUC -- those stay on IU-Xray.
# =============================================================================

import os, math, numpy as np, pandas as pd
from PIL import Image, ImageDraw
from tqdm import tqdm
import matplotlib.pyplot as plt

# --- edit these two paths ----------------------------------------------------
NIH_BBOX_CSV = "/content/drive/MyDrive/msc_medical_vlm_weights_final/nih_chestxray/BBox_List_2017.csv"
NIH_IMG_DIR  = "/content/drive/MyDrive/msc_medical_vlm_weights_final/nih_chestxray/images/"
SAVE_DIR     = "/content/drive/MyDrive/msc_medical_vlm_weights_final"


# -----------------------------------------------------------------------------
# 1. Metrics
# -----------------------------------------------------------------------------
def pointing_game(heatmap, box):
    y, x = np.unravel_index(np.argmax(heatmap), heatmap.shape)
    x0, y0, x1, y1 = box
    return float((x0 <= x <= x1) and (y0 <= y <= y1))

def iou_at_threshold(heatmap, box, thr=0.5):
    hm = heatmap.astype(np.float32)
    hm = (hm - hm.min()) / (hm.max() - hm.min() + 1e-8)
    pred = hm >= thr
    gt = np.zeros_like(pred, dtype=bool)
    x0, y0, x1, y1 = [int(v) for v in box]
    gt[max(0,y0):max(0,y1), max(0,x0):max(0,x1)] = True
    inter = np.logical_and(pred, gt).sum()
    union = np.logical_or(pred, gt).sum()
    return float(inter) / float(union + 1e-8)

def rescale_box(box_xywh, orig_wh, target_wh):
    x, y, w, h = box_xywh
    ow, oh = orig_wh
    tw, th = target_wh
    sx, sy = tw / ow, th / oh
    return (x*sx, y*sy, (x+w)*sx, (y+h)*sy)


# -----------------------------------------------------------------------------
# 2. CSV loader -- robust to NIH's exact column naming
# -----------------------------------------------------------------------------
def load_nih_boxes(csv_path):
    df = pd.read_csv(csv_path)
    df.columns = [c.strip() for c in df.columns]
    # find the filename column (it is literally "Image Index")
    fname_col = [c for c in df.columns if "Image" in c][0]
    label_col = [c for c in df.columns if "Finding" in c][0]
    # the four geometry columns, in order, are everything else minus any
    # trailing unnamed columns NIH sometimes appends
    geo = [c for c in df.columns
           if c not in (fname_col, label_col) and not c.startswith("Unnamed")]
    geo = geo[:4]
    out = pd.DataFrame({
        "fname": df[fname_col].astype(str),
        "label": df[label_col].astype(str),
        "bx": pd.to_numeric(df[geo[0]], errors="coerce"),
        "by": pd.to_numeric(df[geo[1]], errors="coerce"),
        "bw": pd.to_numeric(df[geo[2]], errors="coerce"),
        "bh": pd.to_numeric(df[geo[3]], errors="coerce"),
    }).dropna(subset=["bx", "by", "bw", "bh"])
    return out


# -----------------------------------------------------------------------------
# 3. Main loop
# -----------------------------------------------------------------------------
def run_nih_localization(max_images=None, score_cam=True):
    boxes = load_nih_boxes(NIH_BBOX_CSV)
    if max_images is not None:
        boxes = boxes.iloc[:max_images]

    rows, missing = [], 0
    for r in tqdm(boxes.itertuples(index=False), total=len(boxes),
                  desc="NIH transfer eval"):
        img_path = os.path.join(NIH_IMG_DIR, r.fname)
        if not os.path.exists(img_path):
            missing += 1
            continue
        image = Image.open(img_path).convert("RGB")
        orig_wh = image.size                       # (W, H)
        prompt = get_random_clinical_prompt()

        maps = {
            "Ours":     vlm_cross_attention(image),
            "Grad-CAM": vlm_gradcam(image, prompt),
            "HiResCAM": vlm_hirescam(image, prompt),
        }
        if score_cam:
            maps["Score-CAM"] = vlm_scorecam(image, prompt)

        target_wh = (maps["Ours"].shape[1], maps["Ours"].shape[0])  # (W,H)
        box = rescale_box((r.bx, r.by, r.bw, r.bh), orig_wh, target_wh)

        for method, hm in maps.items():
            rows.append({
                "image": r.fname, "finding": r.label, "method": method,
                "pointing_game": pointing_game(hm, box),
                "iou": iou_at_threshold(hm, box, thr=0.5),
            })

    if missing:
        print(f"[warn] {missing} images listed in CSV not found in {NIH_IMG_DIR}")
    return pd.DataFrame(rows)


def summarise_nih(df):
    g = df.groupby("method").agg(
        pointing_game=("pointing_game", "mean"),
        iou=("iou", "mean"),
        n=("pointing_game", "size"),
    )
    order = [m for m in ["Grad-CAM", "HiResCAM", "Score-CAM", "Ours"]
             if m in g.index]
    return g.loc[order]


def nih_to_latex(summary):
    lines = [r"\begin{tabular}{lccc}", r"\toprule",
             r"Method & Pointing Game $\uparrow$ & IoU@0.5 $\uparrow$ & $n$ \\",
             r"\midrule"]
    for m in summary.index:
        row = summary.loc[m]
        name = r"\textbf{Cross-Attention (Ours)}" if m == "Ours" else m
        lines.append(f"{name} & {row.pointing_game:.3f} & "
                     f"{row.iou:.3f} & {int(row.n)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


# -----------------------------------------------------------------------------
# 4. SANITY CHECK -- run this FIRST on 1 image before trusting any number.
#    Overlays the rescaled box on each method's heatmap so you can SEE that
#    boxes and maps share a coordinate frame.
# -----------------------------------------------------------------------------
def sanity_overlay(row_idx=0, score_cam=True):
    boxes = load_nih_boxes(NIH_BBOX_CSV)
    r = boxes.iloc[row_idx]
    img_path = os.path.join(NIH_IMG_DIR, r.fname)
    assert os.path.exists(img_path), f"not found: {img_path}"
    image = Image.open(img_path).convert("RGB")
    orig_wh = image.size
    prompt = get_random_clinical_prompt()

    maps = {
        "Ours":     vlm_cross_attention(image),
        "Grad-CAM": vlm_gradcam(image, prompt),
        "HiResCAM": vlm_hirescam(image, prompt),
    }
    if score_cam:
        maps["Score-CAM"] = vlm_scorecam(image, prompt)

    n = len(maps)
    fig, axes = plt.subplots(1, n, figsize=(4*n, 4))
    if n == 1:
        axes = [axes]
    for ax, (name, hm) in zip(axes, maps.items()):
        tw, th = hm.shape[1], hm.shape[0]
        x0, y0, x1, y1 = rescale_box((r.bx, r.by, r.bw, r.bh), orig_wh, (tw, th))
        ax.imshow(hm, cmap="jet")
        ax.add_patch(plt.Rectangle((x0, y0), x1-x0, y1-y0,
                     fill=False, edgecolor="white", lw=2))
        py, px = np.unravel_index(np.argmax(hm), hm.shape)
        ax.scatter([px], [py], c="cyan", s=40, marker="x")
        hit = (x0 <= px <= x1) and (y0 <= py <= y1)
        ax.set_title(f"{name}\n{r.label} | {'HIT' if hit else 'miss'}")
        ax.axis("off")
    plt.tight_layout()
    plt.savefig(f"{SAVE_DIR}/nih_sanity_overlay.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("White box = GT pathology; cyan x = heatmap peak. "
          "Peak inside box = pointing-game hit.")


# -----------------------------------------------------------------------------
# 5. RUN
# -----------------------------------------------------------------------------
# STEP 1 -- look before you leap: confirm boxes line up with heatmaps.
sanity_overlay(row_idx=0, score_cam=False)

# STEP 2 -- quick pass (skip slow Score-CAM first time).
nih_df = run_nih_localization(max_images=50, score_cam=False)
print(summarise_nih(nih_df).round(3))

# STEP 3 -- full run when you're happy (uncomment):
# nih_df = run_nih_localization(max_images=None, score_cam=True)
# nih_summary = summarise_nih(nih_df)
# print(nih_summary.round(3))
# print("\n% ---- paste into paper ----")
# print(nih_to_latex(nih_summary))
# nih_df.to_csv(f"{SAVE_DIR}/nih_localization_raw.csv", index=False)
# nih_summary.to_csv(f"{SAVE_DIR}/nih_localization_summary.csv")

# -----------------------------------------------------------------------------
# 5. RUN
# -----------------------------------------------------------------------------
# STEP 1 -- look before you leap: confirm boxes line up with heatmaps.
# We loop through the first 3 indices to print them with Score-CAM enabled.
for i in range(3):
    print(f"\n--- Printing Sanity Check for Image Index: {i} (with Score-CAM) ---")
    sanity_overlay(row_idx=i, score_cam=True)

# STEP 2 -- Run for 50 images including Score-CAM
# Note: This will be slower due to Score-CAM's forward passes!
print("\n--- Running Evaluation on 50 images with Score-CAM ---")
nih_df = run_nih_localization(max_images=50, score_cam=True)

# Print the summary
summary = summarise_nih(nih_df)
print("\nFinal Summary Table:")
print(summary.round(3))

# Print LaTeX code for your paper
print("\n% ---- paste into paper ----")
print(nih_to_latex(summary))